Debug information for file: javali_tests/fromHWcopied/HW4_homei/SimpleTest.javali
AST Resulting From Parsing Stage:
ClassDecl (name: A, superClass: Object)
| VarDecl (name: x, type: int)
| MethodDecl (argumentNames: [], argumentTypes: [], name: foo, returnType: void)
| | Seq ()
| | Seq ()
| | | BuiltInWrite ()
| | | | Var (name: x)
| MethodDecl (argumentNames: [], argumentTypes: [], name: funA, returnType: void)
| | Seq ()
| | Seq ()
ClassDecl (name: B, superClass: A)
| MethodDecl (argumentNames: [], argumentTypes: [], name: funB, returnType: void)
| | Seq ()
| | Seq ()
| MethodDecl (argumentNames: [], argumentTypes: [], name: foo, returnType: void)
| | Seq ()
| | Seq ()
ClassDecl (name: Main, superClass: Object)
| VarDecl (name: a, type: A)
| VarDecl (name: b, type: B)
| VarDecl (name: g, type: int)
| MethodDecl (argumentNames: [], argumentTypes: [], name: main, returnType: void)
| | Seq ()
| | | VarDecl (name: c, type: int[])
| | Seq ()
| | | Assign ()
| | | | Var (name: c)
| | | | NewArray (typeName: int[])
| | | | | IntConst (value: 3)
| | | Assign ()
| | | | Var (name: a)
| | | | NewObject (typeName: A)
| | | Assign ()
| | | | Var (name: b)
| | | | NewObject (typeName: B)
| | | Assign ()
| | | | Field (fieldName: x)
| | | | | Var (name: a)
| | | | IntConst (value: 5)
| | | Assign ()
| | | | Var (name: g)
| | | | Field (fieldName: x)
| | | | | Var (name: a)
| | | Assign ()
| | | | Index ()
| | | | | Var (name: c)
| | | | | IntConst (value: 0)
| | | | MethodCallExpr (methodName: loc)
| | | | | ThisRef ()
| | | | | BinaryOp (operator: B_PLUS)
| | | | | | Var (name: g)
| | | | | | IntConst (value: 1)
| | | BuiltInWrite ()
| | | | Index ()
| | | | | Var (name: c)
| | | | | IntConst (value: 0)
| MethodDecl (argumentNames: [arg], argumentTypes: [int], name: loc, returnType: int)
| | Seq ()
| | Seq ()
| | | Assign ()
| | | | Var (name: arg)
| | | | BinaryOp (operator: B_PLUS)
| | | | | Var (name: arg)
| | | | | IntConst (value: 2)
| | | ReturnStmt ()
| | | | Var (name: arg)

Test failed because an exception was thrown:
    definitions must have (local) variable on LHS
Stack trace:
java.lang.IllegalArgumentException: definitions must have (local) variable on LHS
	at cd.transform.analysis.ReachingDefsAnalysis$Def.<init>(ReachingDefsAnalysis.java:112)
	at cd.ir.ControlFlowGraph.generateGenKillDefSet(ControlFlowGraph.java:106)
	at cd.transform.analysis.ReachingDefsAnalysis.<init>(ReachingDefsAnalysis.java:38)
	at cd.util.debug.ReachingDefsDump.toString(ReachingDefsDump.java:32)
	at cd.AbstractTestAgainstFrozenReference.testReachingDefsAnalysis(AbstractTestAgainstFrozenReference.java:215)
	at cd.AbstractTestAgainstFrozenReference.test(AbstractTestAgainstFrozenReference.java:60)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
